# Generated by Django 2.1.4 on 2018-12-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo_main',
            field=models.ImageField(upload_to='properties'),
        ),
    ]
