# Generated by Django 2.1.4 on 2019-03-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_is_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_rent',
            field=models.BooleanField(default=True),
        ),
    ]
