# Generated by Django 2.1.4 on 2019-03-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20190324_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lot_size',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
